services:
    test-client:
        volumes:
            - ./sample_data_config/ci-ejp-xml-data-pipeline.config.yaml:/ejp_xml_pipeline/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml
            - ./credentials.json:/root/.config/gcloud/credentials.json
            - ~/.aws/credentials:/root/.aws/credentials
