version: '3.4'

services:
    webserver:
        ports:
            - "8080:8080"
        volumes:
            - ./credentials.json:/tmp/credentials.json
            - ~/.aws/credentials:/home/airflow/.aws/credentials

    scheduler:
        volumes:
            - ./credentials.json:/tmp/credentials.json
            - ~/.aws/credentials:/home/airflow/.aws/credentials

    worker:
        volumes:
            - ./sample_data_config/ci-ejp-xml-data-pipeline.config.yaml:/home/airflow/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml
            - ./credentials.json:/tmp/credentials.json
            - ~/.aws/credentials:/home/airflow/.aws/credentials

    test-client:
        volumes:
            - ./sample_data_config/ci-ejp-xml-data-pipeline.config.yaml:/home/airflow/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml
            - ./credentials.json:/tmp/credentials.json
            - ~/.aws/credentials:/home/airflow/.aws/credentials
