version: '3.4'

x-airflow-env:
  &airflow-env
  - LOAD_EX=n
  - AIRFLOW_HOST=webserver
  - AIRFLOW_PORT=8080
  - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
  - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
  - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  - AIRFLOW__CORE__FERNET_KEY='81HqDtbqAywKSOumSha3BhWNOdQ26slT6K0YaZeZyPs='
  - AIRFLOW__SMTP__SMTP_HOST=smtp-server
  - AIRFLOW__SMTP__SMTP_STARTTLS=False
  - AIRFLOW__SMTP__SMTP_SSL=False
  - AIRFLOW__SMTP__SMTP_PORT=25
  - AIRFLOW__SMTP__SMTP_MAIL_FROM=do-no-reply@domain.com
  - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default
  - GOOGLE_APPLICATION_CREDENTIALS=/home/airflow/.config/gcloud/credentials.json
  - DEPLOYMENT_ENV=ci
  - EJP_XML_CONFIG_FILE_PATH=/home/airflow/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml


services:
    data-hub-dags:
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
        build:
            context: .
        image: elifesciences/data-hub-ejp-xml-pipeline
        command: ''

    data-hub-dags-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image:  elifesciences/data-hub-ejp-xml-pipeline-dev
        command: /bin/sh -c exit 0
        entrypoint: []

    webserver:
        depends_on:
            - worker
        environment: *airflow-env
        image:  elifesciences/data-hub-ejp-xml-pipeline-dev
        entrypoint: /entrypoint
        command: webserver

    smtp-server:
        restart: always
        image:  namshi/smtp@sha256:aa63b8de68ce63dfcf848c56f3c1a16d81354f4accd4242a0086c57dd5a91d77

    scheduler:
        image: elifesciences/data-hub-ejp-xml-pipeline-dev
        depends_on:
            - postgres
        environment: *airflow-env
        entrypoint: /entrypoint
        command: scheduler

    worker:
        environment: *airflow-env
        depends_on:
          - smtp-server
          - redis
          - scheduler
        image: elifesciences/data-hub-ejp-xml-pipeline-dev
        entrypoint: /entrypoint
        hostname: worker
        command: >
            bash -c "sudo install -D /tmp/credentials.json -m 644 -t  /home/airflow/.config/gcloud
            && airflow worker"

    test-client:
        image:  elifesciences/data-hub-ejp-xml-pipeline-dev
        depends_on:
            - scheduler
            - webserver
        environment: *airflow-env
        command: >
            bash -c "sudo install -D /tmp/credentials.json -m 644 -t  /home/airflow/.config/gcloud
            && ./run_test.sh with-end-to-end"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U airflow"]
            interval: 5s
            timeout: 5s
            retries: 5
    
    redis:
        image: redis:5.0.5
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    flower:
        image: elifesciences/data-hub-ejp-xml-pipeline-dev
        depends_on:
            - redis
        environment: *airflow-env
        ports:
            - "5555:5555"
        command: celery flower
