version: '3.4'

x-pipeline-env:
  &pipeline-env
  - LOAD_EX=n
  - GOOGLE_APPLICATION_CREDENTIALS=/home/airflow/.config/gcloud/credentials.json
  - DEPLOYMENT_ENV=ci
  - EJP_XML_CONFIG_FILE_PATH=/home/airflow/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml


services:
    data-hub-pipelines:
        environment: *pipeline-env
        build:
            context: .
        image: ${IMAGE_REPO}:${IMAGE_TAG}
        command: ''

    data-hub-pipelines-dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        command: /bin/sh -c exit 0
        entrypoint: []

    test-client:
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        environment: *pipeline-env
        command: >
            bash -c "sudo install -D /tmp/credentials.json -m 644 -t  /home/airflow/.config/gcloud
            && ./run_test.sh with-end-to-end"

