version: '3.4'

services:
    data-hub-pipelines-dev:
        volumes:
            - ./tests:/ejp_xml_pipeline/tests
            - ./ejp_xml_pipeline:/ejp_xml_pipeline/ejp_xml_pipeline

    test-client:
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/credentials.json
            - ./sample_data_config/ci-ejp-xml-data-pipeline.config.yaml:/ejp_xml_pipeline/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml
            - ~/.aws/credentials:/root/.aws/credentials

    data-hub-pipelines:
        volumes:
            - ~/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/credentials.json
            - ./sample_data_config/ejp-xml-data-pipeline.config.yaml:/ejp_xml_pipeline/app-config/ejp-xml/ejp-xml-data-pipeline.config.yaml
            - ~/.aws/credentials:/root/.aws/credentials
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/credentials.json
        user: 0:0
