[project]
name = "data-hub-ejp-xml-pipeline"
version = "0.0.0"
description = "eJP XML Data Pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bigquery-schema-generator>=1.6.1",
    "boto3>=1.24.59",
    "botocore>=1.27.59",
    "google-cloud-bigquery>=3.40.1",
    "lxml>=6.0.2",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2026.1.post1",
    "pyyaml>=6.0.3",
    "six>=1.17.0",
    "typing-extensions>=4.15.0",
    "urllib3>=2.6.3,<2.7",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "pylint>=4.0.5",
    "pytest>=8.4.2",
    "pytest-watch>=4.2.0",
    "types-python-dateutil>=2.9.0.20260408",
    "types-pytz>=2026.1.1.20260408",
    "types-pyyaml>=6.0.12.20260408",
    "types-requests>=2.31.0.2",
]
