gcpProjectName: 'elife-data-pipeline'
dataPipelineId: ejp_xml_pipeline_id
dataset: '{ENV}'
manuscriptTable: 'manuscript_truncated_{ENV}'
manuscriptVersionTable: 'manuscript_version_truncated_{ENV}'
personTable: 'person_truncated_{ENV}'
personVersion2Table: 'person_v2_truncated_{ENV}'
eJPXmlBucket: 'ci-elife-data-pipeline'
eJPXmlObjectKeyPattern: 'airflow_test/ejp-xml-test-data/ejp_elife_*'
stateFile:
  bucket: '{ENV}-elife-data-pipeline'
  object: 'airflow-config/ejp-xml/{ENV}-ejp-xml-processing-state-always_deleted.json'
