gcpProjectName: 'elife-data-pipeline'
dataPipelineId: ejp_xml_pipeline_id
dataset: '{ENV}'
manuscriptTable: 'sample_manuscript'
manuscriptVersionTable: 'sample_manuscript_version'
personTable: 'sample_person'
personVersion2Table: 'sample_person_v2'
eJPXmlBucket: 'elife-ejp-ftp-db-xml-dump'
eJPXmlObjectKeyPattern: 'ejp_eLife_*'
stateFile:
  bucket: '{ENV}-elife-data-pipeline'
  object: 'airflow-config/ejp-xml/ejp-xml-processing-state-test.json'
tempS3FileStorage:
  bucket: '{ENV}-elife-data-pipeline'
  objectPrefix: 'airflow-config/ejp-xml/{ENV}-temp-ejp-xml'
