gcpProjectName: 'elife-data-pipeline'
dataPipelineId: ejp_xml_pipeline_id
dataset: '{ENV}'
manuscriptTable: 'sample_manuscript'
manuscriptVersionTable: 'sample_manuscript_version'
personTable: 'sample_person'
personVersion2Table: 'sample+person_v2'
eJPXmlBucket: 'ci-elife-data-pipeline'
eJPXmlObjectKeyPattern: 'airflow_test/ejp-xml-test-data/ejp_elife_*'
stateFile:
  bucket: '{ENV}-elife-data-pipeline'
  object: 'airflow-config/ejp-xml/{ENV}-ejp-xml-processing-state-test_k.json'
